### ISSUE TITLE
Ludovic Wrote to the devel list

### ISSUE THREAD

**Issue by IAHM-COL** [FGMEMBERS/707#2] opened 2015-05-16 22:04 UTC
Dear Mark @D-MKF1 
Ludovic Brenta sent the following message to the devel list.

He has full write permission over all aircraft on the FGAddon. If he commits this to FGADdon, my script will rebase his commit back to FGMEMBERs repository within 48h.

If you want to stop, consider emailing the devel list.
You can also consider just leave the patch come, or revert it when it merges into FGMEMBERs.

Best,
Israel @IAHM-COL

---

> Permission to commit the following patch?  I discovered this bug while
> running fgrun under strace and determined that fgrun would try, and
> obviously fail, to load
> /home/lbrenta/.fgfs/Aircraft/707/Aircraft/707/Models/Cockpit/Manual/manual.xml.
> Consequently it would only show the 707 Passenger in its list of
> aircraft.
> 
> If nobody objects within 24h, I'll go ahead and commit.
> 
> Date:   Sat May 16 23:02:13 2015 +0200
> 
>    707: make it load in fgrun
> 
>    707-common.xml: while <model><path> elements need the Aircraft/707/
>     prefix for multiplayer, include="" attributes do not need it and
> the
>     prefix actually prevents the 707, 707-TT, EC137-D from loading in
>     fgrun; only the 707-PAX would load because this is the only -set
> file
>     that does not include 707-common.xml.
> 
> <pre>
> diff --git a/707-common.xml b/707-common.xml
> index 4160bb5..e0c037d 100644
> --- a/707-common.xml
> +++ b/707-common.xml
> @@ -438,7 +438,7 @@
>                        '<text3 type="string"'>FOR FLIGHTGEAR SIMULATION ONLY'</text3'>
>                       <subtitle4 type="string"></subtitle4>
>                      <text4 type="string">Lake of Constance Hangar Vol. 1.1.5</text4>
> -                       <content include="Aircraft/707/Models/Cockpit/Manual/manual.xml"/>
> +                       <content include="Models/Cockpit/Manual/manual.xml"/>
>                 </manual>
>                 <ground-service>
>                         <fuel-truck>
> </pre>
## 

> Ludovic Brenta.

**Comment by IAHM-COL** [comment] 2015-05-16 22:09
Full patch can be seen here

http://sourceforge.net/p/flightgear/mailman/flightgear-devel/thread/562809b8e3b42d7f47d53e17d2e0ee1f%40ludovic-brenta.org/#msg34118900

**Comment by JWocky** [comment] 2015-05-16 22:13
What the hell is this? Ludovic tries to break the 707 on FGADDON?

**Comment by ghost** [comment] 2015-05-16 22:42
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I can confirm this bug in the latest SVN version of fgrun, but I
cannot believe that this is a bug of 707, because the 707 could load
with this setting for quiet a long time, until the last update of FGRUN.

(The "last" means last week, because personally I don't build FG and
FGRUN everyday.)

Bo

On 05/16/2015 06:13 PM, JWocky wrote:

> What the hell is this? Ludovic tries to break the 707 on FGADDON?
> 
> On 05/16/2015 05:04 PM, Israel Hernandez wrote:
> 
> > Dear Mark @D-MKF1 https://github.com/D-MKF1 Ludovic Brenta sent
> > the following message to the devel list.
> > 
> > He has full write permission over all aircraft on the FGAddon. If
> > he commits this to FGADdon, my script will rebase his commit back
> > to FGMEMBERs repository within 48h.
> > 
> > If you want to stop, consider emailing the devel list. You can
> > also consider just leave the patch come, or revert it when it 
> > merges into FGMEMBERs.
> > 
> > Best, Israel @IAHM-COL https://github.com/IAHM-COL
> > 
> > Permission to commit the following patch? I discovered this bug
> > while running fgrun under strace and determined that fgrun would
> > try, and obviously fail, to load 
> > /home/lbrenta/.fgfs/Aircraft/707/Aircraft/707/Models/Cockpit/Manual/manual.xml.
> > 
> > Consequently it would only show the 707 Passenger in its list of
> > aircraft.
> > 
> > If nobody objects within 24h, I'll go ahead and commit.
> > 
> > Date: Sat May 16 23:02:13 2015 +0200
> > 
> > |  707: make it load in fgrun
> > 
> > 707-common.xml: while <model><path> elements need the
> > Aircraft/707/ prefix for multiplayer, include="" attributes do
> > not need it and |
> > 
> > the prefix actually prevents the 707, 707-TT, EC137-D from
> > loading in fgrun; only the 707-PAX would load because this is the
> > only -set file that does not include 707-common.xml.
> > 
> > diff --git a/707-common.xml b/707-common.xml index
> > 4160bb5..e0c037d 100644 --- a/707-common.xml +++
> > b/707-common.xml @@ -438,7 +438,7 @@ FOR FLIGHTGEAR SIMULATION
> > ONLY
> > 
> > Lake of Constance Hangar Vol. 1.1.5
> > 
> > *
> > 
> > *
> > 
> > Ludovic Brenta.
> > 
> > — Reply to this email directly or view it on GitHub 
> > https://github.com/FGMEMBERS/707/issues/2.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/FGMEMBERS/707/issues/2#issuecomment-102704702
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v1

iQIcBAEBAgAGBQJVV8inAAoJEBpbhaQfQsHCUIYQAJLmGCAWd2W3O6VBDLVFE5NC
9b24ZgK/ibARZEypGD3GOLtuyoznbrwP5t3FKc7pVuL0uRNNlZlNfll9apKMQ/RN
1QEUrOfMSJR0seFpWVVufCpJeG8W8u8pUery9mocg43xIpTvdoZy7gjNr+JLDBkk
gaCrLI8E1qiS3Gd2HUBPB+Y9YwwE5gnupSETHGl0tpRrc5UCeHKWQtgGDVHuT9oR
wckpaV0wsov65tk9tApSysO3vsSE994Dj4l3E4ThqctzY135xxM77BBn+B21/MvY
PDrBVtuDvJiW+FG3kSVoFxeNewpJU8PfWPoRboiifgKWjaoVVWloE8GaRfG257Xc
HRNy9/JA3KK3+NVAPKOjbBYShGoGRgF5IH/7mT4scOUyXjI9nyOvJ5AHirO/raiO
wYng43XBVGQGz7QqvlBMLq4je3VdEGo98zVTYatWBaLcgvvVW4UTIk7KBJwVQUJE
TbrmzbbsqHKdT885EZi5L3D+kg3JRXnJ7gLF6VkYdEti3kt0zgN35OTpEp85DhKr
DNRHlPmxwmUi1qCOQ4oHpkc6OJAB87kbH+CSQ8vL3Jt1KwEHDJb79b8OjWs61v9o
ZPeP+PeCXvJvbqWLqIN8ih8GtO9A4ge7bgQSvtFum1XxQvhDe1cjO25nHdYN9J5w
IWPaa55HQ7QF8z6rXNA6
=dltO
-----END PGP SIGNATURE-----

**Comment by FGDATA** [comment] 2015-05-17 01:59
I am not sure. But it is surprising to me that Ludovic wants to send
commits over the 707 on FGAddon
Hopefully Mark can take a look, because, I have no idea, myself if this
patch is good or not

Israel

**Comment by FGDATA** [comment] 2015-05-19 17:15
This case is finished and fixed by;

https://github.com/FGMEMBERS/707/commit/dc1b38e70387bf687583660d7be85c20803a8a5a
https://github.com/FGMEMBERS/707/commit/ab6069e7cb5beeb27687c3685bd3cfd25fdb9dfa

**Closed as completed** 2015-05-19 17:15 UTC
